// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eufdpcfimmvzzjvqfsar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1ZmRwY2ZpbW12enpqdnFmc2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODg3MDEsImV4cCI6MjA2MjQ2NDcwMX0.av4_3k1jjWChPraOAsJK45Tnn4-eHaH7s375eSaCyLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);